Update patch set 1
Patch Set 1:

ERROR: Command failed: 
 # /usr/bin/dnf builddep --installroot /var/lib/mock/cloud8s-openstack-victoria-el8-build-91820-731922/root/ /var/lib/mock/cloud8s-openstack-victoria-el8-build-91820-731922/root//builddir/build/SRPMS/openstack-nova-22.2.0-1.el8.src.rpm --setopt=tsflags=nocontexts
Package gnupg2-2.2.20-2.el8.aarch64 is already installed.
Package git-2.27.0-1.el8.aarch64 is already installed.
Package openstack-macros-2020.1.2-1.el8.noarch is already installed.
Package python3-setuptools-41.6.0-1.el8.noarch is already installed.
Error: 
 Problem: package python3-os-vif-2.2.0-2.el8.noarch requires python3-ovsdbapp >= 0.12.1, but none of the providers can be installed
  - package python3-ovsdbapp-1.6.0-1.el8.noarch requires python3-openvswitch, but none of the providers can be installed
  - conflicting requests
  - nothing provides python3-openvswitch2.13 needed by python3-rdo-openvswitch-1:2.13-2.el8.noarch

Patch-set: 1