Update patch set 1
Patch Set 1:

Appears to be an issue with OVS dependencies:

Error: Package: 1:openvswitch-2.10.1-1.el7.x86_64 (delorean-master-testing)
           Requires: librte_ethdev.so.8()(64bit)
           Available: dpdk-17.11-13.el7.x86_64 (extras)
               librte_ethdev.so.8()(64bit)
           Available: dpdk-17.11-15.el7.x86_64 (extras)
               librte_ethdev.so.8()(64bit)
           Installing: dpdk-18.11-2.el7_6.x86_64 (extras)
              ~librte_ethdev.so.11()(64bit)

https://trunk.rdoproject.org/centos7-master-head/e8/66/e866846373b55393c097d6b32b16590a282b758f_3f92697b/rpmbuild.log

Patch-set: 1
Reviewer: Gerrit User 142 <142@270e2033-b340-4cff-9539-693957ebf0e7>
Label: Workflow=0