Update patch set 1
Patch Set 1:

storing the error since logs will GCed eventually:

 + rdo_release_review -u rdo-trunk -c RDO -e dev@lists.rdoproject.org -r train -n commit:e2c8dfe5c
 2020-08-28 19:10:31 - INFO: Running rdo_auto_release in /home/zuul directory
 2020-08-28 19:10:33 - INFO: Processing review 748383
 2020-08-28 19:10:33 - INFO: Processing releases for review 748383
 Traceback (most recent call last):
   File "/home/zuul/.venv/bin/rdo_release_review", line 8, in <module>
     sys.exit(main())
   File "/home/zuul/.venv/lib/python3.6/site-packages/rdorelease/rdo_release_review.py", line 312, in main
     process_reviews(args)
   File "/home/zuul/.venv/lib/python3.6/site-packages/rdorelease/rdo_release_review.py", line 278, in process_reviews
     new_pkgs = new_pkgs_review(review, inforepo)
   File "/home/zuul/.venv/lib/python3.6/site-packages/rdorelease/rdo_release_review.py", line 100, in new_pkgs_review
     new_releases = releases_utils.get_new_releases_review(review)
   File "/home/zuul/.venv/lib/python3.6/site-packages/rdoutils/releases_utils.py", line 48, in get_new_releases_review
     new_release = get_release_info(new_release_f)
   File "/home/zuul/.venv/lib/python3.6/site-packages/rdoutils/releases_utils.py", line 18, in get_release_info
     deliverable = yaml.safe_load(release_content)
   File "/home/zuul/.venv/lib64/python3.6/site-packages/yaml/__init__.py", line 162, in safe_load
     return load(stream, SafeLoader)
   File "/home/zuul/.venv/lib64/python3.6/site-packages/yaml/__init__.py", line 112, in load
     loader = Loader(stream)
   File "/home/zuul/.venv/lib64/python3.6/site-packages/yaml/loader.py", line 34, in __init__
     Reader.__init__(self, stream)
   File "/home/zuul/.venv/lib64/python3.6/site-packages/yaml/reader.py", line 85, in __init__
     self.determine_encoding()
   File "/home/zuul/.venv/lib64/python3.6/site-packages/yaml/reader.py", line 124, in determine_encoding
     self.update_raw()
   File "/home/zuul/.venv/lib64/python3.6/site-packages/yaml/reader.py", line 178, in update_raw
     data = self.stream.read(size)
 AttributeError: 'NoneType' object has no attribute 'read'
 ERROR
 {
   "delta": "0:00:25.313659",
   "end": "2020-08-28 19:10:33.297259",
   "msg": "non-zero return code",
   "rc": 1,
   "start": "2020-08-28 19:10:07.983600"
 }

Patch-set: 1