Requires python2-os-traits >= 0.16.0
To support upgrade we need to make sure
os-traits is atleast 0.16.0 since Nova
requires it or crashes at:

nova/virt/driver.py line 115
AttributeError: 'module' object has no attribute
'COMPUTE_IMAGE_TYPE_AKI'

Change-Id: Ib21b33b8117e0121bfac5e9fc312ad923b9ed5f7